import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Picture } from "../components/Picture";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <Picture />
        <div className="text-xl uppercase">Juan Israel</div>
      </main>
    </>
  );
};

export default Home;
